/* eslint-disable max-len */
import Head from 'next/head';
import Image from 'next/image';

import ContactForm from 'components/Contact';
import HeroContentWrapper from 'components/Hero';
import CaseStudySection from 'components/CaseStudySection';
import Phones from 'components/Phones';
import MouseFollowProvider from 'components/MouseFollowProvider';
import PortfolioSlider from 'components/PortfolioSlider';

import { postageTextData } from 'data/data';

import { sanityClient } from 'lib/sanity.server';
import { projectQuery } from 'lib/sanity.queries';

export default function PostageHealth({ projects }) {
  return (
    <>
      <Head>
        <title>Postage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroContentWrapper theme="light" isEllipseAbsent>
        <h1 className="hero__title with-lines">Postage</h1>
        <p className="hero__subtitle subtitle-animated">
          Brand Identity • Web Design • Development
        </p>
      </HeroContentWrapper>

      <CaseStudySection
        section="overview"
        data={postageTextData.overview}
        isOverview
        sectionIndex="01"
      >
        <div className="full-width-phone section-dark">
          <MouseFollowProvider theme="postage-dark">
            <Image
              src="https://cdn.sanity.io/images/vanqukwj/production/f3532b9a6e5f849ce96515310cd3cc4b814cbc84-611x665.png"
              alt="phones"
              width={100}
              height={100}
              unoptimized
              className="first-phone"
            />
          </MouseFollowProvider>
        </div>
      </CaseStudySection>
      <CaseStudySection
        section="Brand Identity"
        sectionIndex="02"
        data={postageTextData.brandIdentity}
      >
        <div className="content-container templated">
          <div className="brands-wrapper">
            <div className="brands-wrapper__white">
              <div className="square">
                <Image
                  src="https://cdn.sanity.io/images/vanqukwj/production/b5cf0ae1bdacd367245d4566166c358c380b4487-191x144.svg"
                  alt="Postage Health"
                  width={100}
                  height={100}
                  unoptimized
                />
              </div>
            </div>
            <div className="brands-wrapper__dark">
              <div className="square">
                <Image
                  src="https://cdn.sanity.io/images/vanqukwj/production/ef0f598a1218f88a277590ebb295b3afe2cb54c7-191x144.svg"
                  alt="Postage Health"
                  width={100}
                  height={100}
                  unoptimized
                />
              </div>
            </div>
          </div>

          <Image
            src="https://cdn.sanity.io/images/vanqukwj/production/e169f0db09a71bdd489b5805500ee498d07a4e0f-1221x542.png"
            alt="Postage Health"
            width={100}
            height={100}
            unoptimized
          />

          <div className="pitch-deck">
            <span>
              pitch deck <br /> design
            </span>
            <Image
              src="https://cdn.sanity.io/images/vanqukwj/production/c255188ecd1a147a42437cc838db5d7cfb0527df-1221x544.png"
              alt="Postage Health"
              width={100}
              height={100}
              unoptimized
            />
          </div>
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="Home Page"
        sectionIndex="03"
        data={postageTextData.homePage}
      >
        <div className="content-container templated">
          <Image
            src="https://cdn.sanity.io/images/vanqukwj/production/9e66750cd9ff7e23a42ea1e2cad7bc6b56ed9a36-1390x4263.png"
            alt="Postage Health"
            width={100}
            height={100}
            unoptimized
          />
        </div>
        <Phones theme="postage" />
      </CaseStudySection>

      <CaseStudySection
        section="How it Works"
        sectionIndex="04"
        data={postageTextData.howItWorks}
      >
        <div className="content-container how-it-works templated">
          <Image
            src="https://cdn.sanity.io/images/vanqukwj/production/e2728c450c7d4601681d6a97ab40910c1b8e1968-1087x3851.png"
            alt="Postage Health"
            width={100}
            height={100}
            unoptimized
          />
        </div>
        <Phones theme="postage" isExpanded />
      </CaseStudySection>

      <CaseStudySection
        section="Blog page"
        sectionIndex="05"
        data={postageTextData.blog}
      >
        <div className="content-container blog">
          <Image
            src="https://cdn.sanity.io/images/vanqukwj/production/393a7f795bcdec43ce2972d62906e7046e6e17bd-549x1137.png"
            alt="Postage Blog"
            width={100}
            height={100}
            unoptimized
          />
          <Image
            src="https://cdn.sanity.io/images/vanqukwj/production/26e3529c8ffa1b28d7290a8e57511fd9a7698d76-549x1137.png"
            alt="Postage Blog"
            width={549}
            height={1137}
          />
        </div>
      </CaseStudySection>

      <section className="section-dark">
        <MouseFollowProvider theme="postage-dark">
          <CaseStudySection
            dark
            section="Contact page"
            sectionIndex="06"
            data={postageTextData.contact}
          >
            <div className="content-container contact">
              <Image
                src="https://cdn.sanity.io/images/vanqukwj/production/5a310638de2fd6f4f73ad036ed0da0d13279fe35-1064x931.png"
                alt="Postage Health"
                width={100}
                height={100}
                unoptimized
              />
              <Image
                src="https://cdn.sanity.io/images/vanqukwj/production/a2518059c9ae1abbcbeb95e8c353b4c5d2f750b9-1064x850.png"
                alt="Postage Health"
                width={100}
                height={100}
                unoptimized
              />
            </div>
          </CaseStudySection>
        </MouseFollowProvider>
      </section>

      <CaseStudySection
        isResult
        resultSection="result"
        resultTitle="We're proud to say we left our Client's mind thoroughly blown."
        resultText=""
        sectionIndex="07"
        screens="15"
        months="3"
        people="4"
      />
      <PortfolioSlider ourProjects={projects} />
      <ContactForm theme="light" />
    </>
  );
}

export async function getStaticProps() {
  const projects = await sanityClient.fetch(projectQuery);

  return {
    props: {
      projects,
    },
  };
}
