import Head from 'next/head';
import Image from 'next/image';

import ContactForm from 'components/Contact';
import HeroContentWrapper from 'components/Hero';
import CaseStudySection from 'components/CaseStudySection';
import PortfolioSlider from 'components/PortfolioSlider';

import { trainsStationTextData } from 'data/data';

import { sanityClient } from 'lib/sanity.server';
import { projectQuery } from 'lib/sanity.queries';

export default function Trainstation({ projects }) {
  return (
    <>
      <Head>
        <title>Trainstation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroContentWrapper theme="light" isEllipseAbsent>
        <h1
          className="hero__title with-lines"
          style={{
            textTransform: 'none',
          }}
        >
          Tr(ai)nStation
        </h1>
        <p className="hero__subtitle subtitle-animated">
          UI/UX Design & Development
        </p>
      </HeroContentWrapper>
      <CaseStudySection
        section="overview"
        data={trainsStationTextData.overview}
        isOverview
        sectionIndex="01"
      >
        <div className="full-width">
          <Image
            src="/assets/images/trainstation/overview.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="user persona"
        data={trainsStationTextData.userPersona}
        sectionIndex="02"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/persona.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="wireframes"
        data={trainsStationTextData.wireframes}
        sectionIndex="03"
      >
        <div className="full-width">
          <Image
            src="/assets/images/trainstation/wireframes.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="design concept"
        data={trainsStationTextData.concept}
        sectionIndex="04"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/concept.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="Log in | Sign up"
        data={trainsStationTextData.login}
        sectionIndex="05"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/login.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
          <Image
            src="/assets/images/trainstation/login-2.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="Next Workout"
        data={trainsStationTextData.workout}
        sectionIndex="06"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/workout.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
          <Image
            src="/assets/images/trainstation/workout-2.png"
            width={1000}
            height={100}
            alt="trainstation-2"
            unoptimized
          />
          <p className="text-right">
            If for some reason you decide to skip an exercise, the application
            will ask you for a reason so that the artificial intelligence on the
            basis of which this application works can build the next workouts
            for the user in a better way
          </p>
          <Image
            src="/assets/images/trainstation-workout-3.png"
            width={1000}
            height={100}
            alt="trainstation-2"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="My profile"
        data={trainsStationTextData.profile}
        sectionIndex="07"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/profile.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="track an activity"
        data={trainsStationTextData.trackActivity}
        sectionIndex="08"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/activity.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
          <Image
            src="/assets/images/trainstation/activity-2.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="awards"
        data={trainsStationTextData.awards}
        sectionIndex="09"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/awards.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        section="theme"
        data={trainsStationTextData.theme}
        sectionIndex="10"
      >
        <div className="content-container templated">
          <Image
            src="/assets/images/trainstation/theme.png"
            width={1000}
            height={100}
            alt="trainstation"
            unoptimized
          />
        </div>
      </CaseStudySection>

      <CaseStudySection
        isResult
        resultSection="result"
        resultTitle="
        As a result, we got a convenient, exciting web application."
        resultText="The task was to create a convenient, intuitive and 
        attractive and exciting design for a fitness application that 
        office workers of various companies and corporations will be happy to use."
        sectionIndex="11"
        screens="40"
        months="3"
        people="6"
      />

      <PortfolioSlider ourProjects={projects} />
      <ContactForm theme="light" />
    </>
  );
}

export async function getStaticProps() {
  const projects = await sanityClient.fetch(projectQuery);

  return {
    props: {
      projects,
    },
  };
}
