import Head from 'next/head';
import { sanityClient } from 'lib/sanity.server';
import { legalTextQuery } from 'lib/sanity.queries';
import LegalText from 'modules/LegalText';

export default function TermsOfUse({ legalTextContent }) {
  return (
    <>
      <Head>
        <title>Terms of Use</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LegalText legalText={legalTextContent} className="legal-text" />
    </>
  );
}

export async function getStaticProps() {
  const legalTextContent = await sanityClient.fetch(legalTextQuery, {
    slug: 'terms-of-use',
  });

  return {
    props: {
      legalTextContent,
    },
  };
}
